STATS_HOME="stats@home"
STATS_FORCE_QUEUE="stats@force-queue"
STATS_ELECTIONS="stats@elections"
STATS_ELECTIONS_PROBLEMS="stats@elections-problems"
STATS_RECENT_VOTES="stats@recent-votes"
STATS_USER_SEARCH="stats@user-search"
STATS_DELETED_ELECTIONS="stats@deleted-elections"
STATS_UNDELETE_ELECTION="stats@undelete-election"
