#!/bin/bash
set -v
printenv

if [ -f /etc/ci_env ]; then source /etc/ci_env; fi;
if [ "$#" -eq 0 ]; then 
    ARGS="" 
else 
    ARGS="-k $*"
fi;

#export ZEUS_TESTS_VERBOSE=1
export PYTHONPATH=.
export ZEUS_TEST_DATABASE=${ZEUS_TEST_DATABASE-"1"}
export ZEUS_DB=${DB_NAME-"zeus_test_db"}
export ZEUS_DB_USER=${DB_USER-"$(whoami)"}
export ZEUS_DB_PASSWORD=${DB_PASSWORD-""}
export ZEUS_DB_HOST=${DB_HOST-"/var/run/postgresql/"}
export DJANGO_SETTINGS_MODULE=test_settings
export OUTDIR=${CI_REPORT_DIR-".test_report"}

mkdir "$OUTDIR";
echo "OUTDIR: $OUTDIR"

cat .coveragerc > test.coveragerc
cat << EOF >> test.coveragerc
[xml]
output = $OUTDIR/coverage.xml

[html]
directory = $OUTDIR/coverage-html
title = "Zeus Coverage $(date +%F.%R)"
EOF
cat test.coveragerc;

echo "ARGS: $ARGS"

py.test -vv --create-db \
    --cov="." \
    --cov-config=test.coveragerc \
    --cov-report=xml \
    --cov-report=html \
    --junit-xml="$OUTDIR/junit.xml" \
    --html "$OUTDIR/test.html/" \
    --trace-config \
    -s \
    "$ARGS"

EXIT_CODE=$?

rm test.coveragerc;
mv .coverage "$OUTDIR";
exit $EXIT_CODE
