# Generated by Django 2.2.3 on 2019-09-13 18:36

from django.db import migrations, models
import django.db.models.deletion
import helios.datatypes
import helios.datatypes.djangofield
import helios_auth.jsonfield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helios_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50)),
                ('datatype', models.CharField(default='legacy/Election', max_length=250)),
                ('short_name', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('election_type', models.CharField(choices=[('election', 'Election'), ('referendum', 'Referendum')], default='election', max_length=250)),
                ('private_p', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('public_key', helios.datatypes.djangofield.LDObjectField(null=True)),
                ('private_key', helios.datatypes.djangofield.LDObjectField(null=True)),
                ('questions', helios.datatypes.djangofield.LDObjectField(null=True)),
                ('eligibility', helios.datatypes.djangofield.LDObjectField(null=True)),
                ('openreg', models.BooleanField(default=False)),
                ('featured_p', models.BooleanField(default=False)),
                ('use_voter_aliases', models.BooleanField(default=False)),
                ('use_advanced_audit_features', models.BooleanField(default=True)),
                ('randomize_answer_order', models.BooleanField(default=False)),
                ('cast_url', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('frozen_at', models.DateTimeField(default=None, null=True)),
                ('archived_at', models.DateTimeField(default=None, null=True)),
                ('registration_starts_at', models.DateTimeField(default=None, null=True)),
                ('voting_starts_at', models.DateTimeField(default=None, null=True)),
                ('voting_ends_at', models.DateTimeField(default=None, null=True)),
                ('complaint_period_ends_at', models.DateTimeField(default=None, null=True)),
                ('tallying_starts_at', models.DateTimeField(default=None, null=True)),
                ('voting_started_at', models.DateTimeField(default=None, null=True)),
                ('voting_extended_until', models.DateTimeField(default=None, null=True)),
                ('voting_ended_at', models.DateTimeField(default=None, null=True)),
                ('tallying_started_at', models.DateTimeField(default=None, null=True)),
                ('tallying_finished_at', models.DateTimeField(default=None, null=True)),
                ('tallies_combined_at', models.DateTimeField(default=None, null=True)),
                ('result_released_at', models.DateTimeField(default=None, null=True)),
                ('voters_hash', models.CharField(max_length=100, null=True)),
                ('encrypted_tally', helios.datatypes.djangofield.LDObjectField(null=True)),
                ('result', helios.datatypes.djangofield.LDObjectField(null=True)),
                ('result_proof', helios_auth.jsonfield.JSONField(null=True)),
                ('help_email', models.EmailField(max_length=254, null=True)),
                ('election_info_url', models.CharField(max_length=300, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helios_auth.User')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, helios.datatypes.LDObjectContainer),
        ),
        migrations.CreateModel(
            name='VoterFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_file', models.FileField(max_length=250, null=True, upload_to='voters/%Y/%m/%d')),
                ('voter_file_content', models.TextField(null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processing_started_at', models.DateTimeField(null=True)),
                ('processing_finished_at', models.DateTimeField(null=True)),
                ('num_voters', models.IntegerField(null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helios.Election')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50)),
                ('voter_login_id', models.CharField(max_length=100, null=True)),
                ('voter_password', models.CharField(max_length=100, null=True)),
                ('voter_name', models.CharField(max_length=200, null=True)),
                ('voter_email', models.CharField(max_length=250, null=True)),
                ('alias', models.CharField(max_length=100, null=True)),
                ('vote', helios.datatypes.djangofield.LDObjectField(null=True)),
                ('vote_hash', models.CharField(max_length=100, null=True)),
                ('cast_at', models.DateTimeField(null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helios.Election')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helios_auth.User')),
            ],
            options={
                'unique_together': {('election', 'voter_login_id')},
            },
            bases=(models.Model, helios.datatypes.LDObjectContainer),
        ),
        migrations.CreateModel(
            name='ElectionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=500)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helios.Election')),
            ],
        ),
        migrations.CreateModel(
            name='CastVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', helios.datatypes.djangofield.LDObjectField()),
                ('vote_hash', models.CharField(max_length=100)),
                ('vote_tinyhash', models.CharField(max_length=50, null=True, unique=True)),
                ('cast_at', models.DateTimeField(auto_now_add=True)),
                ('quarantined_p', models.BooleanField(default=False)),
                ('released_from_quarantine_at', models.DateTimeField(null=True)),
                ('verified_at', models.DateTimeField(null=True)),
                ('invalidated_at', models.DateTimeField(null=True)),
                ('cast_ip', models.GenericIPAddressField(null=True)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helios.Voter')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, helios.datatypes.LDObjectContainer),
        ),
        migrations.CreateModel(
            name='AuditedBallot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_vote', models.TextField()),
                ('vote_hash', models.CharField(max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helios.Election')),
            ],
        ),
        migrations.CreateModel(
            name='Trustee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('secret', models.CharField(max_length=100)),
                ('public_key', helios.datatypes.djangofield.LDObjectField(null=True)),
                ('public_key_hash', models.CharField(max_length=100)),
                ('secret_key', helios.datatypes.djangofield.LDObjectField(null=True)),
                ('pok', helios.datatypes.djangofield.LDObjectField(null=True)),
                ('decryption_factors', helios.datatypes.djangofield.LDObjectField(null=True)),
                ('decryption_proofs', helios.datatypes.djangofield.LDObjectField(null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helios.Election')),
            ],
            options={
                'unique_together': {('election', 'email')},
            },
            bases=(models.Model, helios.datatypes.LDObjectContainer),
        ),
    ]
