# Generated by Django 5.0 on 2025-06-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0005_auto_20210123_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOptOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_hash', models.CharField(help_text='SHA-256 hash of lowercase email', max_length=64, unique=True)),
                ('opted_out_at', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent when opt-out was requested', max_length=500, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address when opt-out was requested', null=True)),
            ],
        ),
    ]
