# Generated by Django 5.0 on 2025-12-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0006_emailoptout'),
        ('helios_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='elections_administered', to='helios_auth.user'),
        ),
    ]
