# Generated by Django 5.2 on 2026-01-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helios", "0007_add_election_admins"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="voter",
            unique_together={("election", "voter_login_id")},
        ),
        migrations.AddField(
            model_name="election",
            name="use_token_auth",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="voter",
            name="voting_token",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="voter",
            unique_together={
                ("election", "voter_login_id"),
                ("election", "voting_token"),
            },
        ),
    ]
