# Generated by Django 5.2.9 on 2026-01-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0007_add_election_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='auto_reminder_enabled_p',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='election',
            name='auto_reminder_hours',
            field=models.IntegerField(default=24, help_text='Hours before voting ends to send reminder (e.g., 24 for one day before)', null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='auto_reminder_sent_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
