from django.conf.urls import patterns, url, include

urlpatterns = patterns(
    '',
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^$', 'account_administration.views.list_users'),
    url(r'^user_list/$', 'account_administration.views.list_users',
        name='list_users'),
    url(r'^user_creation/$', 'account_administration.views.create_user',
        name='create_user'),
    url(r'^institution_creation/$',
        'account_administration.views.create_institution',
        name='create_institution'),
    url(r'institution_list/$',
        'account_administration.views.list_institutions',
        name='list_institutions'),
    url(r'user_management/$',
        'account_administration.views.manage_user',
        name='user_management'),
    url(r'delete_institution/$',
        'account_administration.views.delete_institution',
        name='delete_institution'),
    url(r'inst_deletion_confirmed/$',
        'account_administration.views.inst_deletion_confirmed',
        name='inst_deletion_confirmed'),
    url(r'delete_user/$',
        'account_administration.views.delete_user',
        name='delete_user'),
    url(r'user_deletion_confirmed/$',
        'account_administration.views.user_deletion_confirmed',
        name='user_deletion_confirmed'),
    url(r'reset_password/$',
        'account_administration.views.reset_password',
        name='reset_password'),
    url(r'reset_password_confirmed/$',
        'account_administration.views.reset_password_confirmed',
        name='reset_password_confirmed'),
    )
